### ISSUE TITLE
0.3.0: SyncUpdateError { error_msg: "reader a9143f is not online" }

### ISSUE THREAD

**Issue by Hoohaha** [pravega/pravega-client-rust#327]
**Problem description**

Got below errors when call reader.reader_offline()

```
reader.reader_offline()
pyo3_runtime.PanicException: A Tokio 1.x context was found, but it is being shutdown.
thread '<unnamed>' panicked at 'Update ReaderGroup to ensure reader is offline: SyncError { error_msg: "remove reader Reader { name: \"a9143f\" } and put owned segments {} to unassigned list", source: SyncUpdateError { error_msg: "reader a9143f is not online" } }', src/event/reader.rs:353:18
Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /usr/lib/python3/dist-packages/twisted/internet/asyncioreactor.py:287
handle: <TimerHandle when=23202833.658074833 AsyncioSelectorReactor.callLater.<locals>.run() at /usr/lib/python3/dist-packages/twisted/internet/asyncioreactor.py:287>
pyo3_runtime.PanicException: Update ReaderGroup to ensure reader is offline: SyncError { error_msg: "remove reader Reader { name: \"a9143f\" } and put owned segments {} to unassigned list", source: SyncUpdateError { error_msg: "reader a9143f is not online" } }
```
**Problem location**

**Suggestions for an improvement**

**Comment by Hoohaha** [comment]
How to release reader in a right, To be frankly the python API is too hard to use!

**Comment by tkaitchuck** [comment]
It looks like the reader was already offline. This should be changed to not produce an error.

**Comment by Hoohaha** [comment]
Another question how to continuesly read with Python API.
```python

        self.slice = await self.p_reader.get_segment_slice_async()
        for event in self.slice:
            message = render_log_line(event.data().decode("utf-8", errors="ignore") )
```
or

```python
        while True:
            self.slice = await self.p_reader.get_segment_slice_async()
            for event in self.slice:
                message = render_log_line(event.data().decode("utf-8", errors="ignore") )
```

Seems both cannot do the continues read

**Comment by Hoohaha** [comment]
@tkaitchuck Is there have any workaround for this?

**Comment by shrids** [comment]
Could you check the below code snip that is used for our tests? This should solve the issue you are facing.
https://github.com/pravega/pravega-client-rust/blob/3d7d946513d34944d3a1c8a77acb13f63fc849bd/python_binding/tests/pravega_reader_test.py#L228-L233

A segment slice needs to be returned. This is used by the readers to update the state of the readers and the number of events that have been processed by the user. Once the consumed segment slice is returned a new segment slice is returned by the reader.

**Comment by Hoohaha** [comment]
Hi @shrids @tkaitchuck 

Unfortunately it still happen. In my use case, I implented websocket based on django channel, in websocket read data from pravega stream and forward to user web endpoint. Sometimes you known the websocket may closed unexpectedly, so the error occured again.

**Comment by shrids** [comment]
Hi, I think you are referring to a scenario where the reader is already offline. 
```
SyncUpdateError { error_msg: "reader a9143f is not online" }
```
If the reader is already offline then the RUST code should be changed to not produce this error.

**Comment by Hoohaha** [comment]
yes, i agree, just produce warnings instead of rasise error in there.
Or another possible solution is provide an attribute to present the reader online status. so we can do pre check to avoid such error.
